customCommands:
- key: '<c-g>'
  description: 'Generate commit message (copy to clipboard)'
  context: 'files'
  command: 'gitmsg | pbcopy && echo "Commit message copied to clipboard!"'
  loadingText: 'Generating commit message...'

git:
  overrideGpg: true
