customCommands:
- key: '<c-g>'
  description: 'Generate commit message (copy to clipboard)'
  context: 'global'
  command: 'gitmsg | pbcopy'
  loadingText: 'Generating commit message...'

git:
  overrideGpg: true
